version: '3.8'
services:
  web:
    build: app/.
    image: pyweb-server:latest
    container_name: dashboard_prod
    expose:
      - "8000"
    restart: always
    depends_on:
      - cache

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./config/pyweb_nginx.conf:etc/nginx/conf.d/pyweb_nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - cache

  cache:
    image: redis:alpine
    container_name: redis_cache
    restart: always
